### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by ever4cyth** [bcgsc/HLAminer#1]
According to readme-first in test-demo folder

For HLAminer predictions from short Read Alignments, run:
./HPRArnaseq_classI.sh

Running bwa...
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln_core] calculate SA coordinate... ./HPRArnaseq_classI.sh: line 3: 189118 Segmentation fault      (core dumped) bwa aln -e 0 -o 0 ../database/HLA_ABC_CDS.fasta rd1.fq > aln_test.1.sai
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln_core] calculate SA coordinate... ./HPRArnaseq_classI.sh: line 4: 189120 Segmentation fault      (core dumped) bwa aln -e 0 -o 0 ../database/HLA_ABC_CDS.fasta rd2.fq > aln_test.2.sai
[fread] Unexpected end of file
Predicting HLA...

both v1.3 and v1.3.1 gave the same error. Could you please help? Thanks!

**Comment by warrenlr** [comment]
were the bwa index built with the same version as the one used for alignments?  If not, you must re-build the index of the reference HLA sequences with the version of bwa installed on your system.
Cheers,
Rene

**Comment by nyzhoulang** [comment]
one of the ways is that lower your bwa version to match the HLAminer
