### ISSUE TITLE
Could the software use mouse data for HLA typing?  Or only use human data?

### ISSUE THREAD

**Issue by zhangyafeng1** [bcgsc/HLAminer#11]
HI，
I have data from a group of mouse. could I use HLAminer for HLA typing?  Or HLAminer can only be used to process human data? 
Thank you very much !
Your answer will help me a lot！

**Comment by warrenlr** [comment]
thank you for your interest in HLAminer.

Yes, it was developed for human application and is intended for human typing. 
It has never been tested on different species.

That said, in theory, there's no reason why it couldn't work on mouse. You would need to build MHC gene databases for mouse, and hopefully there are comprehensive gene sets. If the MHC allele naming convention is the same in other species (group, allele, etc), then the package should work as-is, if you point the script to your mouse database.

hope it helps!
Rene
