### ISSUE TITLE
Empty output of HLAminer on PacBio sample

### ISSUE THREAD

**Issue by NTNguyen13** [bcgsc/HLAminer#12]
Hi, I'm analyzing HLA PacBio Long-read amplicon (https://github.com/PacificBiosciences/DevNet/wiki/HLA-Multiplexed-GenDx-Amplicons-HLA-A-,-B,--C,--DQB1,-and--DRB1)

I used minimap -ax pacbio for alignment of fastq to bam, then sort the output. Then I use HLAminer on the final bam file:

`HLAminer.pl -h ../HLAminer-1.4/database/HLA-I_II_GEN.fasta -s 500 -q 1 -i 1 -p ../HLAminer-1.4/database/hla_nom_p.txt -a $file_bam_sorted `

However, the output of HLAminer_HPRA.csv is empty (no allele found). The log is as follow:

```
Alignments to HLA
-----------------
legend
+:Coding variant seen by another contig previously
RBH:Reciprocal Best Hit (if applicable)

Contig/Read pair,HLA [% HSP/% CONTIG/READ PAIR]

----------------------------------------------------------------------
Gene,HLA Supertype/Group,Protein coding allele,Score,Validated by N Contigs,x=contig seen,Chance (%),Expect (Eval) value,Confidence Score (-10 * log10(P))
*Score = sum(Sz * cov * seq.id. * 2 [RBH])
*P HLA = (P tig1 is HLA * P HLA is tig 1) * (P tig2 is HLA * P HLA is tig 2) * .. * (P tig(n) is HLA * P HLA is tig n) where P tig x is HLA = sum(P HLA for tig x)
----------------------------------------------------------------------

HLA-A

HLA-B

HLA-C

HLA-E

HLA-F

HLA-G

HLA-DPA1

HLA-DPB1

HLA-DQA1

HLA-DQB1

HLA-DRA

HLA-DRB1

HLA-DRB2

HLA-DRB3

HLA-DRB4

HLA-DRB5

HLA-DRB6

HLA-DRB7

HLA-DRB8

HLA-DRB9

------------------------------------------------------------------------------------------
SUMMARY 
MOST LIKELY HLA-I ALLELES (Confidence (-10 * log10(Eval)) >= 1 Score >= 500)
Gene,Prediction rank,Group,Allele,Score,Expect (Eval) value,Confidence (-10 * log10(Eval))
------------------------------------------------------------------------------------------

HLA-A

HLA-B

HLA-C

HLA-E

HLA-F

HLA-G


------------------------------------------------------------------------------------------
SUMMARY 
MOST LIKELY HLA-II ALLELES (Confidence (-10 * log10(Eval)) >= 1 Score >= 500)
Gene,Prediction rank,Group,Allele,Score,Expect (Eval) value,Confidence (-10 * log10(Eval))
------------------------------------------------------------------------------------------

HLA-DPA1

HLA-DPB1

HLA-DQA1

HLA-DQB1

HLA-DRA

HLA-DRB1

HLA-DRB2

HLA-DRB3

HLA-DRB4

HLA-DRB5

HLA-DRB6

HLA-DRB7

HLA-DRB8

HLA-DRB9
```

Could you please help me on solving this problem please? Thank you very much

**Comment by warrenlr** [comment]
Does the log show any predictions?  Perhaps you need to reduce the score cutoff (-s) ..  but not easy for me to troubleshoot w/o any output logs. Also, possible that your HLA signal is too low or that your reads aren't mapping properly.

**Comment by NTNguyen13** [comment]
No, it's empty without any predictions. I actually copy-paste the log file to the post above without the command section:

```
/home/nguyen/Exec/HLAminer-1.4/bin/HLAminer.pl [v1.4]
Derivation of HLA class I and II predictions from shotgun sequence datasets
-b NA
-r NA
-c NA
-a /mnt/Data/PacBio_sample_old//bam/lbc8.sorted.bam
-e 0
-h /home/nguyen/Exec/HLAminer-1.4/database/HLA-I_II_GEN.fasta
-p /home/nguyen/Exec/HLAminer-1.4/database/hla_nom_p.txt
-z 200
-i 1
-q 1
-s 500
-n 0
```

**Comment by warrenlr** [comment]
you could run samtools stats on the bam file?   No log/predictions with a direct read alignment method may be due to absence of suitable signal (troubleshoot by lowering -s, try as low as -s 1). But running a diagnostic on your bam file is a must. You may also compare step-by-step with the demo offered with the distribution, to see how the bam file and the analysis steps compare.  

Hope it helps & thank you for your interest in HLAminer
Rene

**Comment by alisamatisse** [comment]
I am having the same issue now, the demo runs okay. The output for my .bam file has no predictions, though. It has a good coverage of 6:32541543-32701886, so I expected to see at least something. It seems that there is something else that is not working. 

perl HLAminer.pl -h ../database/HLA-I_II_GEN.fasta -s 500 -q 30 -i 99 -p ../database/hla_nom_p.txt -a ../../../DNA02_FA1846_ss_5ng_1plex_1.bam

```
Running HLAminer.pl [v1.4]
Derivation of HLA class I and II predictions from shotgun sequence datasets
-b NA
-r NA
-c NA
-a ../../../DNA02_FA1846_ss_5ng_1plex_1.bam
-e 0
-h ../database/HLA-I_II_GEN.fasta
-p ../database/hla_nom_p.txt
-z 200
-i 99
-q 30
-s 500
-n 0
Reading p-nomenclature file ../database/hla_nom_p.txt...
Reading HLA reference sequence file ../database/HLA-I_II_GEN.fasta...
reading alignments [Mon May 13 10:12:01 CEST 2024]
Reading read alignments file ../../../DNA02_FA1846_ss_5ng_1plex_1.bam, please be patient...
done. taking top hits per query [Mon May 13 10:12:13 CEST 2024]
done. reporting alignments [Mon May 13 10:12:13 CEST 2024]
HLAminer_HPRA log written to HLAminer_HPRA.log
done. HLAminer_HPRA predictions written to HLAminer_HPRA.csv [Mon May 13 10:12:13 CEST 2024]

```

Setting score to -s 1 did not help either, or changing other parameters.. the log file is empty

**Comment by warrenlr** [comment]
Could you please provide the command you ran for the alignment (how you generated the bam).

It is important to generate an MD tag in the alignment output. The tool requires it for predictions.  Take a look at the demos for the bwa and minimap2 commands. 

e.g.
minimap2 -t 60 -ax map-ont --MD

**Comment by alisamatisse** [comment]
Hi René, 
Yes, I think the problem was with the --MD tag, thanks! So I ran the demo again, it is fine. Hopefully, my actual data with minimap2 remapping works now. I will let you know

**Comment by warrenlr** [comment]
awesome, keep us posted @alisamatisse !
René

**Comment by alisamatisse** [comment]
Hi René, 

all is working well now, thanks! I am still curious about some things.. but feel bad to ask so much. What would be a "good" score and expect for what I find? 

for example: 

for one person
single prediction DQA1*05:01P, score: 7673.89, expect: 1.64E-27

and **another sample** of the same person:
single prediction DQA1*01:02P, score: 13500.6, expect: 3.44E-30

hm.... I would trust the 2nd sample, but honestly I am not sure how to interpret this!!

Thanks
Alisa

**Comment by warrenlr** [comment]
Hi Alisa, 

A higher score means more sequencing bases support a given HLA allele. But because HLAminer does not look at specific HLA-specific variant bases to make inference, it is possible that a high score wrongly identifies an allele. But in general, higher score, low-expect is a good proxy for the likelihood of the allele identified (of course many factors have to be taken into account, sequencing depth, base quality, etc).

Best,
Rene
