### ISSUE TITLE
Questions about command line and results

### ISSUE THREAD

**Issue by kwanghoon821** [bcgsc/HLAminer#13]
Hi, I used HLAminer for the first time using WES data generated from FFPE sample.

Can you check my command and results?

This is for alignment
bwa mem -t 20 -M path/to/database_bwamem/HLA-I_II_CDS.fasta A_1.fastq.gz A_2.fastq.gz > HLAminer_A.sam 

This is for typing
path/to/HLAminer.pl -a HLAminer_A.sam \
-h path/to/database_bwamem/HLA-I_II_CDS.fasta \
-p path/to/database/hla_nom_p.txt \
-l A_result

And this is results in csv file.
No result for HLA-A,B,C,E

HLA-F 
Prediction   #1 - F*01 |   |  
F*01:01:03:01 | 2413.96 | 7.78E-17 | 161.1
F*01:01P | 1614.99 | 1.82E-11 | 107.4

HLA-G 
Prediction   #1 - G*01 |  
G*01:01P | 1614 | 2.56E-14 | 135.9
G*01:04P | 1008 | 3.20E-09 | 84.9

Log file has results of HLA-A,B,C,E.
Should I see log file?

Thank you!

**Comment by warrenlr** [comment]
hello, thanks for your message and interest in HLAminer.

Predictions only appear in the csv file if they meet the minimum thresholds:

```
prompt> ./HLAminer.pl 
Usage: ./HLAminer.pl [v1.4]

-i minimum % sequence identity...............<99>
-q minimum log10 (phred-like) expect value...<30>
-s minimum score.............................<1000>
```

The log will track everything. You may wish to lower the above thresholds to see predictions in the csv, but at the risk of a lower confidence in predictions.

Lastly, know that WES isn't the typical use-case for HLAminer, as certain HLA alleles may not be picked up by exon capture probes.

good luck!

**Comment by kwanghoon821** [comment]
> hello, thanks for your message and interest in HLAminer.
> 
> Predictions only appear in the csv file if they meet the minimum thresholds:
> 
> ```
> prompt> ./HLAminer.pl 
> Usage: ./HLAminer.pl [v1.4]
> 
> -i minimum % sequence identity...............<99>
> -q minimum log10 (phred-like) expect value...<30>
> -s minimum score.............................<1000>
> ```
> 
> The log will track everything. You may wish to lower the above thresholds to see predictions in the csv, but at the risk of a lower confidence in predictions.
> 
> Lastly, know that WES isn't the typical use-case for HLAminer, as certain HLA alleles may not be picked up by exon capture probes.
> 
> good luck!

Wow, thank you for quick and nice advice.

I will do your advice!
