### ISSUE TITLE
Does HLAminer work for the Nanopore RNA-seq data?

### ISSUE THREAD

**Issue by wt2015-github** [bcgsc/HLAminer#16]
If yes, which pl script is the best one? Thanks!

**Comment by warrenlr** [comment]
We provided an initial solution for WGS nanopore reads 3 years ago, it is documented here, with example command/script:

https://github.com/bcgsc/HLAminer#predicting-from-nanopore-reads-

It's not fully tested, however, so use caution in interpreting its output/predictions.

It should be possible to adapt the commands to work with RNA-Seq reads instead.  You could run something like:

`HPRAcds_ONTclassI-IIdemo.sh myRNAseqONT.fa.gz`

This script is not in the distribution, but after fetching `http://www.bcgsc.ca/downloads/btl/hlaminer/GCA_000001405.15_GRCh38_genomic.chr-only-noChr6-HLA-I_II_CDS.fa.gz` and updating the `../database/HLA-I_II_CDS.fasta` file, it should run. Again, I urge caution in interpreting the output, as it has not been tested.

```
HPRAcds_ONTclassI-IIdemo.sh 
echo "Predicting HLA from raw RNA-seq ONT reads..." 
echo "Fetching database for alignment..."
wget http://www.bcgsc.ca/downloads/btl/hlaminer/GCA_000001405.15_GRCh38_genomic.chr-only-noChr6-HLA-I_II_CDS.fa.gz
####
echo "Running minimap2 (minimap2-2.12-r827) and HLAminer v1.4 combined ..."
/usr/bin/time -v -o minimap_hlaminerRNASEQont_CDS.time minimap2 -t 60 -ax map-ont --MD GCA_000001405.15_GRCh38_genomic.chr-only-noChr6-HLA-I_II_CDS.fa.gz $1 | ../bin/HLAminer.pl -h ../database/HLA-I_II_CDS.fasta -s 500 -q 1 -i 1 -p ../database/hla_nom_p.txt -a stream
mv HLAminer_HPRA.csv HLAminer_HPRA_$1.csv
mv HLAminer_HPRA.log HLAminer_HPRA_$1.log
```
