### ISSUE TITLE
clarification on input

### ISSUE THREAD

**Issue by afadda1** [bcgsc/HLAminer#27]
hi, it's not clear to me what's the input in the two modes of action of the tool. 
HPTASR (HLA Predictions by Targeted Assembly of Shotgun Reads):
-b blastn alignments.........................
OR
HPRA (HLA Predictions by Read Alignment):
-a sam alignments............................< -a ngs_vs_hla.sam > or < -a stream >

can you give examples, and explain the steps needed to prepare the input?
thanks

**Comment by warrenlr** [comment]
Thanks for reaching out and your interest in HLAminer.

Note that HLAminer is a pipeline comprised of several steps, explained in the documentation. 

Examples and test runs, which we encourage you to run, are located in the test-demo folder -- Please consult the README-FIRST.txt in that directory and the readme.md for details on the pipeline (bash scripts) and how to execute. Depending on your data format and type (i.e. short read, long read & RNA-seq, WGS, exome), you would run a different bash script. This is detailed in the readme.md, the demo folder and the bash scripts themselves.

**Comment by afadda1** [comment]
Hi,

I tried to run the example but it gives a segmentation fault

bwa aln -e 0 -o 0 /gpfs/software/genomics/HLAminer/HLAminer_v1.3.1/database/HLA-I_II_CDS.fasta  /gpfs/software/genomics/HLAminer/HLAminer_v1.3.1/test-demo/rd1.fq >aln_test.sai

[bwa_aln] 17bp reads: max_diff = 2

[bwa_aln] 38bp reads: max_diff = 3

[bwa_aln] 64bp reads: max_diff = 4

[bwa_aln] 93bp reads: max_diff = 5

[bwa_aln] 124bp reads: max_diff = 6

[bwa_aln] 157bp reads: max_diff = 7

[bwa_aln] 190bp reads: max_diff = 8

[bwa_aln] 225bp reads: max_diff = 9

[bwa_aln_core] calculate SA coordinate... Segmentation fault


I’m using BWA/0.7.17/

Thanks,
From: René ***@***.***>
Reply-To: bcgsc/HLAminer ***@***.***>
Date: Wednesday, 11 January 2023 at 16:51
To: bcgsc/HLAminer ***@***.***>
Cc: afadda1 ***@***.***>, Author ***@***.***>
Subject: Re: [bcgsc/HLAminer] clarification on input (Issue #27)


Thanks for reaching out and your interest in HLAminer.

Note that HLAminer is a pipeline comprised of several steps, explained in the documentation.

Examples and test runs, which we encourage you to run, are located in the test-demo folder -- Please consult the README-FIRST.txt in that directory and the readme.md for details on the pipeline (bash scripts) and how to execute. Depending on your data format and type (i.e. short read, long read & RNA-seq, WGS, exome), you would run a different bash script. This is detailed in the readme.md, the demo folder and the bash scripts themselves.

**Comment by warrenlr** [comment]
`[bwa_aln_core] calculate SA coordinate... Segmentation fault`

this is a bwa error, no an HLAminer error. 

[Worth checking bwa's homepage or bioinformatics support channels ](https://www.biostars.org/p/283661/)
