### ISSUE TITLE
homozygous alleles

### ISSUE THREAD

**Issue by afadda1** [bcgsc/HLAminer#28]
hi again,

when only one prediction is presented, does that mean the locus is homozygous?
thanks

**Comment by warrenlr** [comment]
not necessarily. It's possible that the score of the other allele falls below set thresholds and are therefore not reported (with confidence). Low coverage sequencing data may also fail to assemble into a sufficient large-enough contig (or map to a locus if you're using the direct alignment method).

**Comment by afadda1** [comment]
how would i know?
here's an example:

HLA-G
--
Prediction #1 - G*01
G*01:01:12

**Comment by warrenlr** [comment]
Please have a look at the log to see what HLA-G alleles your contigs or reads are hitting. The logs are daunting, but the information in it is extensive. You could grep all HLA-G hits are summarize them.

One thing to keep in mind is that HLA-G is a non-classical HLA allele with very low diversity, esp. in the coding (either coding synonymous or intronic mutations).  Homozygous calls are probably expected for this group. You would likely have to drill down to 6 or 8-digit+ to see difference in resolution, well beyond the resolution of HLAminer.

Take a look at :

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4186343/

**Comment by afadda1** [comment]
I have thousands of samples and so many genes that the tool types. It’s impractical and daunting to look at the log files.
But thank you anyway. I hope you implement a way to do this automatically. Until then, I will rely on other tools.


From: René ***@***.***>
Reply-To: bcgsc/HLAminer ***@***.***>
Date: Wednesday, 8 February 2023 at 14:54
To: bcgsc/HLAminer ***@***.***>
Cc: afadda1 ***@***.***>, Author ***@***.***>
Subject: Re: [bcgsc/HLAminer] homozygous alleles (Issue #28)


Please have a look at the log to see what HLA-G alleles your contigs or reads are hitting. The logs are daunting, but the information in it is extensive. You could grep all HLA-G hits are summarize them.

One thing to keep in mind is that HLA-G is a non-classical HLA allele with very low diversity, esp. in the coding (either coding synonymous or intronic mutations). Homozygous calls are probably expected for this group. You would likely have to drill down to 6 or 8-digit+ to see difference in resolution, well beyond the resolution of HLAminer.

Take a look at :

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4186343/
