### ISSUE TITLE
What is HLA

### ISSUE THREAD

**Issue by asan-emirsaleh** [bcgsc/HLAminer#29]
Hello!
I wondered that there is no place in the README where the meaning of the HLA is described. It was not clear for me untill I started to search on NCBI. The first meaning I thought about was "homosigous locus {allele/alignment}", but now it became clear to be "human leukocyte antigen". If the description were in abbreviation one could easily understand what for this project was dedicated.

**Comment by warrenlr** [comment]
fixed.
