### ISSUE TITLE
What is the purpose of patient.fof?

### ISSUE THREAD

**Issue by WQ0829** [bcgsc/HLAminer#30]
Hi, I tried using my .fastq files and wrote the full path in the patient.fof. While I was trying to run HPRAwgs_ONTclassI-IIdemo.sh, it seemed like it is using ERR2585115.fastq.gz instead of my files. Is there a specific place where I should specify to use files in patient.fof?

**Comment by warrenlr** [comment]
patient.fof is only used in conjunction with HLAminer HLA predictions from targeted short read assembly.

Please note that the bash script `HPRAwgs_ONTclassI-IIdemo.sh` is simply a demo script, to test the streaming functionality.

I encourage you to take a look at the preprint for info on how to run on your data. But essentially, you simply need to replace the `ERR2585115.fastq.gz` in this command:

`/usr/bin/time -v -o minimap_hlaminerERR2585115-1mod.time minimap2 -t 60 -ax map-ont --MD ../database/GCA_000001405.15_GRCh38_genomic.chr-only-noChr6-HLA-I_II_GEN.fa.gz ERR2585115.fastq.gz | ./HLAminer.pl -h ../database/HLA-I_II_GEN.fasta -s 500 -q 1 -i 1 -p ../database/hla_nom_p.txt -a stream`

thank you for your interest in HLAminer
