### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by alisamatisse** [bcgsc/HLAminer#33]
Hello, 

I cannot run demo because of the following error
```
Downloading MCF-7 pacbio RNA-seq reads...
--2024-05-12 13:24:56--  http://datasets.pacb.com.s3.amazonaws.com/2013/IsoSeqHumanMCF7Transcriptome/IsoSeq_MCF7_polished.unimapped.fasta
Resolving datasets.pacb.com.s3.amazonaws.com (datasets.pacb.com.s3.amazonaws.com)... 16.182.36.193, 3.5.29.243, 52.217.204.113, ...
Connecting to datasets.pacb.com.s3.amazonaws.com (datasets.pacb.com.s3.amazonaws.com)|16.182.36.193|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-05-12 13:25:01 ERROR 403: Forbidden.
```

anything I am missing? 
Thank you ~~

**Comment by warrenlr** [comment]
It seems that the IsoSeq data is no longer available from PacBio (https://github.com/PacificBiosciences/DevNet/wiki/Iso-Seq-dataset).

To be fair, it is an old (>10years) data set.

I have updated the link for download:

wget http://www.bcgsc.ca/downloads/btl/hlaminer/IsoSeq_MCF7_polished.unimapped.fasta

and the demo (also very old code):
https://github.com/bcgsc/HLAminer/blob/master/HLAminer-1.4/bin/HPRArnaseq_pacbioSEclassI.sh

**Comment by alisamatisse** [comment]
Thanks, the demo works for me now!
