### ISSUE TITLE
The running time is toooooooo looooooooong

### ISSUE THREAD

**Issue by zhangyafeng1** [bcgsc/HLAminer#7]
The script  HPTASRwgs_classI-II.sh   have running  7 days ,,,,,,  my bam file is 7.9G ,
OOOOMMMMMGGGGGGG,,,toooooo loooooooooong..........

**Comment by warrenlr** [comment]
hmm the script HPTASRwgs_classI-II.sh is not processing bam files... so not sure what the relation between the bam file size and this is.  Do you mean your input read set?

On thing that would be helpful is to know which step is taking so long. I suspect TASR, which could be addressed by replacing with a faster multi-threaded assembler..
